/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberos_grupo_87.Vista;

/**
 *
 * @author psg_7
 */
public class gestionCuarteles extends javax.swing.JInternalFrame {

    /**
     * Creates new form gestionCuarteles
     */
    public gestionCuarteles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLgestionCuarteles = new javax.swing.JLabel();
        jLseleccioneCuartelAEliminar = new javax.swing.JLabel();
        jTFmotivosEliminacion = new javax.swing.JTextField();
        jLmotivoEliminacion = new javax.swing.JLabel();
        jCBSeleccioneCartelAEliminar = new javax.swing.JComboBox<>();
        jBeliminarCuartel = new javax.swing.JButton();
        jLeliminarCuartel = new javax.swing.JLabel();

        jLgestionCuarteles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLgestionCuarteles.setText("GESTIÓN DE CUARTELES");

        jLseleccioneCuartelAEliminar.setText("Seleccione el cuartel que desea eliminar:");

        jLmotivoEliminacion.setText("Motivos de la eliminación:");

        jBeliminarCuartel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBeliminarCuartel.setText("Eliminar Cuartel");

        jLeliminarCuartel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLeliminarCuartel.setText("Eliminar Cuartel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLeliminarCuartel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLmotivoEliminacion)
                                .addGap(18, 18, 18)
                                .addComponent(jTFmotivosEliminacion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLseleccioneCuartelAEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jCBSeleccioneCartelAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jBeliminarCuartel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLgestionCuarteles)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLgestionCuarteles)
                .addGap(27, 27, 27)
                .addComponent(jLeliminarCuartel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBSeleccioneCartelAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLseleccioneCuartelAEliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLmotivoEliminacion)
                    .addComponent(jTFmotivosEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jBeliminarCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBeliminarCuartel;
    private javax.swing.JComboBox<String> jCBSeleccioneCartelAEliminar;
    private javax.swing.JLabel jLeliminarCuartel;
    private javax.swing.JLabel jLgestionCuarteles;
    private javax.swing.JLabel jLmotivoEliminacion;
    private javax.swing.JLabel jLseleccioneCuartelAEliminar;
    private javax.swing.JTextField jTFmotivosEliminacion;
    // End of variables declaration//GEN-END:variables
}
