/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberos_grupo_87.Vista;

import bomberos_grupo_87.AccesoADatos.BomberoData;
import bomberos_grupo_87.AccesoADatos.BrigadaData;
import bomberos_grupo_87.Entidades.Bombero;
import bomberos_grupo_87.Entidades.Brigada;
import java.awt.Event;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.time.ZoneId;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author gabriel925
 */
public class GestionBombero extends javax.swing.JInternalFrame {

    BomberoData bd = new BomberoData();

    /**
     * Creates new form GestionBombero
     */
    public GestionBombero() {
        initComponents();
        cargarCombo();
        jtCodBombero.setEditable(false);
        jcbActivo.setEnabled(false);
        iniciarCombo();
        evitarPegar(jtCel);
        evitarPegar(jtCodBombero);
        evitarPegar(jtDni);
        evitarPegar(jtNomAp);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/cascobom.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtCodBombero = new javax.swing.JTextField();
        jtNomAp = new javax.swing.JTextField();
        jtCel = new javax.swing.JTextField();
        jcbActivo = new javax.swing.JCheckBox();
        jdFechNa = new com.toedter.calendar.JDateChooser();
        jcbBrigada = new javax.swing.JComboBox<>();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        ComboSangre = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 0));
        setClosable(true);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        jLabel1.setText("GESTION BOMBERO");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 204, 0));
        jLabel2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel2.setText("DNI :");
        jLabel2.setOpaque(true);

        jtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDniKeyTyped(evt);
            }
        });

        jbBuscar.setBackground(new java.awt.Color(102, 102, 102));
        jbBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbBuscar.setText("BUSCAR");
        jbBuscar.setOpaque(false);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(204, 204, 0));
        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel3.setText("CODIGO DE BOMBERO :");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(204, 204, 0));
        jLabel4.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel4.setText("NOMBRE Y APELLIDO :");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(204, 204, 0));
        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel5.setText("FECHA DE NACIMIENTO :");
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(204, 204, 0));
        jLabel6.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel6.setText("GRUPO SANGUINEO :");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(204, 204, 0));
        jLabel7.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel7.setText("CELULAR :");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(204, 204, 0));
        jLabel8.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel8.setText("CODIGO BRIGADA :");
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(204, 204, 0));
        jLabel9.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jLabel9.setText("ESTADO :");
        jLabel9.setOpaque(true);

        jtCodBombero.setBackground(new java.awt.Color(102, 102, 102));

        jtNomAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNomApKeyTyped(evt);
            }
        });

        jtCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCelKeyTyped(evt);
            }
        });

        jcbActivo.setBackground(new java.awt.Color(204, 204, 0));
        jcbActivo.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jcbActivo.setText("ACTIVO");
        jcbActivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jbEliminar.setBackground(new java.awt.Color(102, 102, 102));
        jbEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbEliminar.setText("ELIMINAR");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGuardar.setBackground(new java.awt.Color(102, 102, 102));
        jbGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbGuardar.setText("GUARDAR");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtCodBombero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtNomAp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtCel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbActivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jdFechNa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbBrigada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ComboSangre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbBuscar)))
                        .addGap(94, 94, 94))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbEliminar)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jtCodBombero, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtNomAp, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                            .addComponent(jtCel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                            .addComponent(jcbActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jdFechNa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbBrigada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboSangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbGuardar)
                                .addGap(149, 149, 149))))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtCodBombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jtNomAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jdFechNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ComboSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jcbBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEliminar)
                    .addComponent(jbGuardar))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        try {
            int dni = Integer.valueOf(jtDni.getText());

            Bombero bv = bd.buscarBomberoPorDNI(dni);
            jtCodBombero.setText(bv.getCodBombero() + "");
            jtNomAp.setText(bv.getNombre_ape());
            jdFechNa.setDate(Date.valueOf(bv.getFecha_nac()));
            ComboSangre.setSelectedItem(bv.getGrupo_sang());
            jtCel.setText(bv.getCelular());
            jcbActivo.setSelected(bv.isEstado());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un DNI Correcto");
            limpiarCampos();
        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        if (jtDni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un numro de dni");
        } else {
            try {
                int dni = Integer.valueOf(jtDni.getText());
                Bombero bv = bd.buscarBomberoPorDNI(dni);
                if (jtCodBombero.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "busque al bombero a eliminar");
                } else {
                    bd.eliminarBombero(bv.getCodBombero());
                }
                limpiarCampos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "DNI incorrecto");
                jtDni.setText("");
            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        if (jtDni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ingrese un DNI y busque el bombero a modificar");
        } else {
            try {
                int dni = Integer.parseInt(jtDni.getText());
                Bombero bv = bd.buscarBomberoPorDNI(dni);
                if (jtCodBombero.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Busque el bombero a modificar");
                } else if (jtDni.getText().isEmpty() || jtNomAp.getText().isEmpty() || jtCel.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Los campos deben estar completos");
                } else {

                    BrigadaData brD = new BrigadaData();
                    Brigada br = (Brigada) jcbBrigada.getSelectedItem();
                    if (brD.listarBomberosPorBrigada(br.getCodBrigada()).size() >= 5) {
                        JOptionPane.showMessageDialog(null, "La brigada esta llena, seleccione otra Brigada");

                    } else {
                        bv.setBrigada((Brigada) jcbBrigada.getSelectedItem());
                        bv.setDni(Integer.valueOf(jtDni.getText()));
                        bv.setNombre_ape(jtNomAp.getText());
                        bv.setGrupo_sang(ComboSangre.getSelectedItem()+"");
                        bv.setCelular(jtCel.getText());
                        bv.setFecha_nac(jdFechNa.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                        bd.modificarBombero(bv);
                        limpiarCampos();
                    }
                }
            } catch (NumberFormatException nf) {
                JOptionPane.showMessageDialog(null, "DNI INCORRECTO");
                limpiarCampos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS DEBEN ESTAR COMPLETOS");
            }
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDniKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 58;

        if (!num) {
            evt.consume();
        }
        
    }//GEN-LAST:event_jtDniKeyTyped

    private void jtNomApKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomApKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();
        boolean min = key >= 65 && key <= 90;
        boolean mayu = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(min || mayu || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtNomApKeyTyped

    private void jtCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCelKeyTyped
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 58;

        if (!num) {
            evt.consume();
        }
    }//GEN-LAST:event_jtCelKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboSangre;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JComboBox<Brigada> jcbBrigada;
    private com.toedter.calendar.JDateChooser jdFechNa;
    private javax.swing.JTextField jtCel;
    private javax.swing.JTextField jtCodBombero;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtNomAp;
    // End of variables declaration//GEN-END:variables
public void limpiarCampos() {
        jtDni.setText("");
        jtNomAp.setText("");
        jtCodBombero.setText("");
        jtCel.setText("");
        jdFechNa.repaint();
        jcbActivo.setSelected(false);

    }

    public void cargarCombo() {
        BrigadaData bd = new BrigadaData();
        for (Brigada brigada : bd.listarBrigadas()) {
            jcbBrigada.addItem(brigada);
        }
    }
    
    private void evitarPegar(JTextField campo) {
        InputMap map2 = campo.getInputMap(JTextField.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

    }

    private void iniciarCombo(){
        ComboSangre.addItem("A+");
        ComboSangre.addItem("A-");
        ComboSangre.addItem("B+");
        ComboSangre.addItem("B-");
        ComboSangre.addItem("AB+");
        ComboSangre.addItem("AB-");
        ComboSangre.addItem("O+");
        ComboSangre.addItem("O-");
    }
}
