/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberos_grupo_87.Vista;

import bomberos_grupo_87.AccesoADatos.CuartelData;
import bomberos_grupo_87.Entidades.Cuartel;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author psg_7
 */
public class nuevoCuartel extends javax.swing.JInternalFrame {
    CuartelData CD = new CuartelData();
    /**
     * Creates new form nuevoCuartel
     */
    public nuevoCuartel() {
        initComponents();
        evitarPegar(JTFCodCuartel);
        evitarPegar(jTFnombreNuevoCuartel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLnuevoCuartel = new javax.swing.JLabel();
        jLnombreCuartel = new javax.swing.JLabel();
        jTFnombreNuevoCuartel = new javax.swing.JTextField();
        jLcodigoCuartel = new javax.swing.JLabel();
        JTFCodCuartel = new javax.swing.JTextField();
        jLDireccion = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLCoordX = new javax.swing.JLabel();
        jTFCoordX = new javax.swing.JTextField();
        jLCoordY = new javax.swing.JLabel();
        jTFCorreo = new javax.swing.JTextField();
        jTFTel = new javax.swing.JTextField();
        jLTel = new javax.swing.JLabel();
        jLestado = new javax.swing.JLabel();
        jTFCoordY = new javax.swing.JTextField();
        jLCorreo = new javax.swing.JLabel();
        jCheckBoxEstado = new javax.swing.JCheckBox();
        jbSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbNuevoCuartel = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLnuevoCuartel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLnuevoCuartel.setForeground(new java.awt.Color(255, 0, 0));
        jLnuevoCuartel.setText("NUEVO CUARTEL");

        jLnombreCuartel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLnombreCuartel.setForeground(new java.awt.Color(255, 0, 0));
        jLnombreCuartel.setText("Nombre del nuevo Cuartel:");

        jTFnombreNuevoCuartel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnombreNuevoCuartelKeyTyped(evt);
            }
        });

        jLcodigoCuartel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLcodigoCuartel.setForeground(new java.awt.Color(255, 0, 0));
        jLcodigoCuartel.setText("Código Cuartel:");

        JTFCodCuartel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCodCuartelKeyTyped(evt);
            }
        });

        jLDireccion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLDireccion.setForeground(new java.awt.Color(255, 0, 0));
        jLDireccion.setText("Dirección:");

        jLCoordX.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLCoordX.setForeground(new java.awt.Color(255, 0, 0));
        jLCoordX.setText("Coordenadas X:");

        jTFCoordX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCoordXActionPerformed(evt);
            }
        });

        jLCoordY.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLCoordY.setForeground(new java.awt.Color(255, 0, 0));
        jLCoordY.setText("Coordenadas Y:");

        jLTel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLTel.setForeground(new java.awt.Color(255, 0, 0));
        jLTel.setText("Teléfono:");

        jLestado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLestado.setForeground(new java.awt.Color(255, 0, 0));
        jLestado.setText("Estado:");

        jLCorreo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLCorreo.setForeground(new java.awt.Color(255, 0, 0));
        jLCorreo.setText("Correo:");

        jCheckBoxEstado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCheckBoxEstado.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBoxEstado.setText("  Activo");

        jbSalir.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 0, 0));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estacion-de-bomberos (1).png"))); // NOI18N

        jbNuevoCuartel.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jbNuevoCuartel.setForeground(new java.awt.Color(255, 0, 0));
        jbNuevoCuartel.setText("Crear Nuevo Cuartel");
        jbNuevoCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoCuartelActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jbBuscar.setForeground(new java.awt.Color(255, 0, 0));
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbModificar.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jbModificar.setForeground(new java.awt.Color(255, 0, 0));
        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLnuevoCuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLnombreCuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTFnombreNuevoCuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLcodigoCuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JTFCodCuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLDireccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTFDireccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLCoordX, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTFCoordX, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLCoordY, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTFCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTFTel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLTel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLestado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTFCoordY, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBoxEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbNuevoCuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLDireccion)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTFCorreo))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLnombreCuartel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addGap(128, 128, 128)
                                            .addComponent(jLnuevoCuartel))
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addComponent(jLcodigoCuartel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JTFCodCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(43, 43, 43)
                                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addComponent(jLCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTFCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                    .addComponent(jLestado)
                                                    .addGap(48, 48, 48))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                                    .addComponent(jLTel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBoxEstado)
                                                .addComponent(jTFCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLCoordY)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTFTel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addGap(75, 75, 75)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jbNuevoCuartel)
                                .addGap(29, 29, 29)
                                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLCorreo)
                        .addGap(10, 10, 10)
                        .addComponent(jTFnombreNuevoCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLnuevoCuartel)
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigoCuartel)
                    .addComponent(JTFCodCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombreCuartel)
                    .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDireccion)
                    .addComponent(jTFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCoordY)
                    .addComponent(jTFCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCorreo)
                    .addComponent(jTFnombreNuevoCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTel))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbNuevoCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLestado)
                            .addComponent(jCheckBoxEstado))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCoordXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCoordXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCoordXActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:        
        if(JTFCodCuartel.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Por favor ingrese un Código válido");
        }else{
        int codCuartel = Integer.valueOf(JTFCodCuartel.getText());
        try{
            
      
        Cuartel cuartel = CD.buscarCuartel(codCuartel);
        if (cuartel == null){
            borrarCampos();            
            JOptionPane.showMessageDialog(this, "No se encontro el cuartel");
            
        } else {
            jTFnombreNuevoCuartel.setText(cuartel.getNombre_cuartel());
            jTFDireccion.setText(cuartel.getDireccion());
            jTFCoordX.setText(cuartel.getCoord_X()+"");
            jTFCoordY.setText(cuartel.getCoord_Y()+"");
            jTFTel.setText(cuartel.getTelefono());
            jTFCorreo.setText(cuartel.getCorreo());
            jCheckBoxEstado.setSelected(cuartel.isEstado());
            
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "No se encontro el cuartel");
        }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        if(JTFCodCuartel.getText().isEmpty() || jTFnombreNuevoCuartel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "NO debe dejar CAMPOS VACIOS.");
        }else{
        int codCuartel = Integer.valueOf(JTFCodCuartel.getText());
        Cuartel cuartel = CD.buscarCuartel(codCuartel);
        cuartel.setNombre_cuartel(jTFnombreNuevoCuartel.getText());
        cuartel.setDireccion(jTFDireccion.getText());
        cuartel.setCoord_X((Integer.valueOf(jTFCoordX.getText())));
        cuartel.setCoord_Y((Integer.valueOf(jTFCoordY.getText())));
        cuartel.setTelefono(jTFTel.getText());
        cuartel.setCorreo(jTFCorreo.getText());
        cuartel.setEstado((jCheckBoxEstado.isSelected()));
        
       
        CuartelData cuartlData = new CuartelData();
        cuartlData.modificarCuartel(cuartel);
        limpiarCampos();
        
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbNuevoCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoCuartelActionPerformed
        // TODO add your handling code here:
        try{
            if(jTFnombreNuevoCuartel.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Ingrese un Nombre para el Nuevo Cuartel");
            }else if(jTFDireccion.getText().isEmpty() || jTFTel.getText().isEmpty()||jTFCorreo.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Todos los Campos deben estar Completos");
            }else if (jCheckBoxEstado.isSelected() == false){
                JOptionPane.showMessageDialog(null, "El Cuartel debe estar Activo");
            }else{
        String nombre_cuartel = jTFnombreNuevoCuartel.getText();
        String direccion = jTFDireccion.getText();
        int coord_x = Integer.parseInt(jTFCoordX.getText());
        int coord_y = Integer.parseInt(jTFCoordY.getText());
        String telefono = jTFTel.getText();
        String correo = jTFCorreo.getText();
        boolean estado = jCheckBoxEstado.isSelected();
        
        Cuartel cuart = new Cuartel (nombre_cuartel, direccion, coord_x, coord_y, telefono, correo, estado);
        CuartelData cuartData = new CuartelData();
        cuartData.crearCuartel(cuart);
        limpiarCampos();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERROR. Verifique que los datos sean correctos"
                    + " en TODOS los campos.");
       
        limpiarCampos();
        }
      
    }//GEN-LAST:event_jbNuevoCuartelActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void JTFCodCuartelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCodCuartelKeyTyped
        // TODO add your handling code here:
         int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 58;

        if (!num) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFCodCuartelKeyTyped

    private void jTFnombreNuevoCuartelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnombreNuevoCuartelKeyTyped
        // TODO add your handling code here:
        /*int key = evt.getKeyChar();
        boolean min = key >= 65 && key <= 90;
        boolean mayu = key >= 97 && key <= 122;
        //boolean espacio = key == 32;

        if (!(min || mayu)) {
            evt.consume();
        }*/
    }//GEN-LAST:event_jTFnombreNuevoCuartelKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFCodCuartel;
    private javax.swing.JCheckBox jCheckBoxEstado;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLCoordX;
    private javax.swing.JLabel jLCoordY;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcodigoCuartel;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLnombreCuartel;
    private javax.swing.JLabel jLnuevoCuartel;
    private javax.swing.JTextField jTFCoordX;
    private javax.swing.JTextField jTFCoordY;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFTel;
    private javax.swing.JTextField jTFnombreNuevoCuartel;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevoCuartel;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
private void limpiarCampos() {
        jTFnombreNuevoCuartel.setText("");
        JTFCodCuartel.setText("");
        jTFDireccion.setText("");
        jTFCoordX.setText("");
        jTFCoordY.setText("");
        jTFTel.setText("");
        jTFCorreo.setText("");
        jCheckBoxEstado.setSelected(false);

        
    }

    private static class CtelData {

        public CtelData() {
        }
    }
    
    public void borrarCampos() {
        jTFnombreNuevoCuartel.setText("");
        JTFCodCuartel.setText("");
        jTFDireccion.setText("");
        jTFCoordX.setText("");
        jTFCoordY.setText("");
        jTFTel.setText("");
        jTFCorreo.setText("");
        jCheckBoxEstado.setSelected(false);

    }
    private void evitarPegar(JTextField campo) {
        InputMap map2 = campo.getInputMap(JTextField.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
}
    
