/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberos_grupo_87.Vista;

import bomberos_grupo_87.AccesoADatos.CuartelData;
import bomberos_grupo_87.AccesoADatos.SiniestroData;
import bomberos_grupo_87.Entidades.Especialidad;
import bomberos_grupo_87.Entidades.Siniestro;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Discar
 */
public class nuevoSiniestro extends javax.swing.JInternalFrame {
    //private CuartelData CD = new CuartelData();
    private SiniestroData SD = new SiniestroData();
    private CuartelData CD = new CuartelData();
    

    /**
     * Creates new form nuevoSiniestro
     */
    public nuevoSiniestro() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextCodSini = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        ComboEsp = new javax.swing.JComboBox<>();
        FechaHora = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDetalles = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        TextCoordX = new javax.swing.JTextField();
        TextCoordY = new javax.swing.JTextField();
        ButtonNuevo = new javax.swing.JButton();
        ButtonModifi = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        LabelEnCurso = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LabelCuartelKM = new javax.swing.JLabel();
        LabelEspecialidad = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO SINIESTRO");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CODIGO DEL SINIESTRO: ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("TIPO DEL SINIESTRO: ");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setText("FECHA Y HORA DEL SINIESTRO: ");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel5.setText("COORDENADAS X: ");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setText("DETALLES: ");

        ButtonBuscar.setText("BUSCAR");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        FechaHora.setDateFormatString("dd-MMM-yyyy HH:mm:ss");

        TextDetalles.setColumns(20);
        TextDetalles.setRows(5);
        jScrollPane1.setViewportView(TextDetalles);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("COORDENADAS Y : ");

        ButtonNuevo.setText("NUEVO");
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });

        ButtonModifi.setText("MODIFICAR");
        ButtonModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModifiActionPerformed(evt);
            }
        });

        ButtonSalir.setText("SALIR");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setText("EN CURSO: ");

        LabelEnCurso.setBackground(new java.awt.Color(51, 51, 51));
        LabelEnCurso.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        LabelEnCurso.setForeground(new java.awt.Color(255, 255, 255));
        LabelEnCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEnCurso.setText("NO");
        LabelEnCurso.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("BRIGADA ESPECIALIZADA: ");
        jLabel11.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("CUARTEL CERCA A: ");
        jLabel12.setOpaque(true);

        LabelCuartelKM.setBackground(new java.awt.Color(51, 51, 51));
        LabelCuartelKM.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        LabelCuartelKM.setForeground(new java.awt.Color(255, 255, 255));
        LabelCuartelKM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCuartelKM.setText("NO");
        LabelCuartelKM.setOpaque(true);

        LabelEspecialidad.setBackground(new java.awt.Color(51, 51, 51));
        LabelEspecialidad.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        LabelEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        LabelEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEspecialidad.setText("NO");
        LabelEspecialidad.setOpaque(true);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextCodSini, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ButtonBuscar))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addComponent(LabelEnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel12))
                                    .addComponent(ButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addComponent(LabelCuartelKM, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(LabelEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addComponent(ButtonModifi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(ButtonSalir)
                                        .addGap(119, 119, 119)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Panel1Layout.createSequentialGroup()
                                        .addComponent(TextCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addComponent(TextCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168))))
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCodSini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ComboEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(TextCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(LabelCuartelKM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonModifi)
                    .addComponent(ButtonNuevo)
                    .addComponent(ButtonSalir))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
        // TODO add your handling code here:
        Siniestro sini;
        //Especialidad:
        Especialidad esp =(Especialidad) ComboEsp.getSelectedItem();
        try{
        LocalDate fyh =(FechaHora.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        int hh = FechaHora.getJCalendar().getDate().getHours();
        int mm = FechaHora.getJCalendar().getDate().getMinutes();
        int ss = FechaHora.getJCalendar().getDate().getSeconds();
        //Fecha y Hora Inicial
        LocalDateTime fechasini=LocalDateTime.of(fyh.getYear(),fyh.getMonth().getValue(),fyh.getDayOfMonth(),hh,mm,ss);
        
        //Coordenadas
        int coorX=(Integer.valueOf(TextCoordX.getText()));
        int coorY=(Integer.valueOf(TextCoordY.getText()));
        //Detalles
        String detalle = TextDetalles.getText();
        
        SD.crearSiniestro(new Siniestro(esp,fechasini,coorX,coorY,detalle,true,false));
        borrarCampos();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Porfavor no deje campos vacios.");
        }
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    private void ButtonModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModifiActionPerformed
        // TODO add your handling code here:
        borrarCampos();
        
    }//GEN-LAST:event_ButtonModifiActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // TODO add your handling code here:
        int codSini = Integer.valueOf(TextCodSini.getText());
        Siniestro sini=SD.buscarSiniestro(codSini);
        
        ComboEsp.setSelectedItem(sini.getEspecialidad());
        //Calendar fecha = sini.getFecha_siniestro()
        //FechaHora.setCalendar(sini.getFecha_siniestro().toLocalTime(),sini.getFecha_siniestro().toLocalDate());
        Calendar ahora = Calendar.getInstance();
        ahora.clear();
        ahora.set(Calendar.YEAR, sini.getFecha_siniestro().getYear());
        ahora.set(Calendar.MONTH, sini.getFecha_siniestro().getMonthValue()-1); //-1 Por que los meses son 0 a 11;
        ahora.set(Calendar.DAY_OF_MONTH, sini.getFecha_siniestro().getDayOfMonth());
        ahora.set(Calendar.HOUR_OF_DAY, sini.getFecha_siniestro().getHour());
        ahora.set(Calendar.MINUTE, sini.getFecha_siniestro().getMinute());
        ahora.set(Calendar.SECOND, sini.getFecha_siniestro().getSecond());
        FechaHora.setCalendar(ahora);
        TextCoordX.setText(String.valueOf(sini.getCoord_X()));
        TextCoordY.setText(String.valueOf(sini.getCoord_Y()));
        TextDetalles.setText(sini.getDetalles());
        if(sini.isEnCurso()==true){
            LabelEnCurso.setText("SI");
        }else{
            LabelEnCurso.setText("NO");
        }
        if(sini.getBrigada()==null){
            LabelCuartelKM.setText("NINGUNO");
            LabelEspecialidad.setText("NINGUNA");
        }else{
            LabelCuartelKM.setText(CD.listaCuartCercaDeSiniestro(sini.getCodSiniestro()).firstKey()+"KM");
            LabelEspecialidad.setText(sini.getBrigada().getEspecialidad().toString());
        }
        
    }//GEN-LAST:event_ButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonModifi;
    private javax.swing.JButton ButtonNuevo;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JComboBox<Especialidad> ComboEsp;
    private com.toedter.calendar.JDateChooser FechaHora;
    private javax.swing.JLabel LabelCuartelKM;
    private javax.swing.JLabel LabelEnCurso;
    private javax.swing.JLabel LabelEspecialidad;
    private javax.swing.JPanel Panel1;
    private javax.swing.JTextField TextCodSini;
    private javax.swing.JTextField TextCoordX;
    private javax.swing.JTextField TextCoordY;
    private javax.swing.JTextArea TextDetalles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo(){
        ComboEsp.addItem(Especialidad.Incendios);
        ComboEsp.addItem(Especialidad.OperativoPrevencion);
        ComboEsp.addItem(Especialidad.RescateAccTrafico);
        ComboEsp.addItem(Especialidad.RescateMontaña);
        ComboEsp.addItem(Especialidad.SalvamentoDerrumbe);
        ComboEsp.addItem(Especialidad.SocorrerInundaciones);
        
    }
    
    private void borrarCampos(){
        TextCoordX.setText("");
        TextCoordY.setText("");
        TextDetalles.setText("");
        LabelEnCurso.setText("NO");
        LabelCuartelKM.setText("NINGUNO");
        LabelEspecialidad.setText("NINGUNO");
        FechaHora.setCalendar(null);
    }
    
}
