/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberos_grupo_87.Vista;

import java.awt.Color;

/**
 *
 * @author Discar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jmBomberoNuevo = new javax.swing.JMenuItem();
        jmBomberoConsulta = new javax.swing.JMenuItem();
        jmBomberoGestion = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        nuevaBrigada = new javax.swing.JMenuItem();
        consultaBrigada = new javax.swing.JMenuItem();
        gestionBrigada = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmNuevoCuartel = new javax.swing.JMenuItem();
        jConsultaCuarteles = new javax.swing.JMenuItem();
        jGestionCuarteles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jMenu1.setText("RECURSOS HUMANOS");

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bombero (1).png"))); // NOI18N
        jMenu6.setText("BOMBEROS");

        jmBomberoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo (1).png"))); // NOI18N
        jmBomberoNuevo.setText("NUEVO");
        jmBomberoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBomberoNuevoActionPerformed(evt);
            }
        });
        jMenu6.add(jmBomberoNuevo);

        jmBomberoConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta (1).png"))); // NOI18N
        jmBomberoConsulta.setText("CONSULTA");
        jmBomberoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBomberoConsultaActionPerformed(evt);
            }
        });
        jMenu6.add(jmBomberoConsulta);

        jmBomberoGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestion (1).png"))); // NOI18N
        jmBomberoGestion.setText("GESTION");
        jmBomberoGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBomberoGestionActionPerformed(evt);
            }
        });
        jMenu6.add(jmBomberoGestion);

        jMenu1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Brigada (1).png"))); // NOI18N
        jMenu7.setText("BRIGADAS");

        nuevaBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo (1).png"))); // NOI18N
        nuevaBrigada.setText("NUEVO");
        nuevaBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaBrigadaActionPerformed(evt);
            }
        });
        jMenu7.add(nuevaBrigada);

        consultaBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta (1).png"))); // NOI18N
        consultaBrigada.setText("CONSULTA");
        consultaBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBrigadaActionPerformed(evt);
            }
        });
        jMenu7.add(consultaBrigada);

        gestionBrigada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestion (1).png"))); // NOI18N
        gestionBrigada.setText("GESTION");
        gestionBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionBrigadaActionPerformed(evt);
            }
        });
        jMenu7.add(gestionBrigada);

        jMenu1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cuartel (1).png"))); // NOI18N
        jMenu8.setText("CUARTELES");
        jMenu8.setToolTipText("");

        jmNuevoCuartel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo (1).png"))); // NOI18N
        jmNuevoCuartel.setText("NUEVO");
        jmNuevoCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNuevoCuartelActionPerformed(evt);
            }
        });
        jMenu8.add(jmNuevoCuartel);

        jConsultaCuarteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta (1).png"))); // NOI18N
        jConsultaCuarteles.setText("CONSULTA");
        jConsultaCuarteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaCuartelesActionPerformed(evt);
            }
        });
        jMenu8.add(jConsultaCuarteles);

        jGestionCuarteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestion (1).png"))); // NOI18N
        jGestionCuarteles.setText("GESTION");
        jGestionCuarteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGestionCuartelesActionPerformed(evt);
            }
        });
        jMenu8.add(jGestionCuarteles);

        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("ADMIN SINIESTROS");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/siniestro.png"))); // NOI18N
        jMenu4.setText("SINIESTROS");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo (1).png"))); // NOI18N
        jMenuItem7.setText("NUEVO");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta (1).png"))); // NOI18N
        jMenuItem9.setText("CONSULTAS");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem1.setText("GESTION");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        menuSalir.setText("SALIR");
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmNuevoCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNuevoCuartelActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        nuevoCuartel NC = new nuevoCuartel();
        NC.setVisible(true);
        NC.getContentPane().setBackground(new Color (153, 153, 153));
        escritorio.add(NC);
        NC.moveToFront();
    }//GEN-LAST:event_jmNuevoCuartelActionPerformed

    private void nuevaBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaBrigadaActionPerformed
        // TODO add your handling code here:
       escritorio.removeAll();
       escritorio.repaint();
       nuevaBrigada nueva = new nuevaBrigada();
       nueva.setVisible(true);
       escritorio.add(nueva);
       nueva.moveToFront();
    }//GEN-LAST:event_nuevaBrigadaActionPerformed

    private void consultaBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBrigadaActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        brigadaConsulta consulta = new brigadaConsulta();
        consulta.setVisible(true);
        escritorio.add(consulta);
        consulta.moveToFront();
    }//GEN-LAST:event_consultaBrigadaActionPerformed

    private void gestionBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionBrigadaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        gestionBrigada gestion = new gestionBrigada();
        gestion.setVisible(true);
        escritorio.add(gestion);
        gestion.moveToFront();
    }//GEN-LAST:event_gestionBrigadaActionPerformed

    private void jmBomberoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBomberoNuevoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        NuevoBombero nb = new NuevoBombero();
        nb.setVisible(true);
        escritorio.add(nb);
        nb.moveToFront();
    }//GEN-LAST:event_jmBomberoNuevoActionPerformed

    private void jmBomberoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBomberoConsultaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaBombero cb = new ConsultaBombero();
        cb.setVisible(true);
        escritorio.add(cb);
        cb.moveToFront();
    }//GEN-LAST:event_jmBomberoConsultaActionPerformed

    private void jmBomberoGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBomberoGestionActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionBombero gb = new GestionBombero();
        gb.setVisible(true);
        escritorio.add(gb);
        gb.moveToFront();
    }//GEN-LAST:event_jmBomberoGestionActionPerformed

    private void jConsultaCuartelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaCuartelesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        consultaCuarteles CCs = new consultaCuarteles();
        CCs.setVisible(true);
        CCs.getContentPane().setBackground(new Color (153, 153, 153));
        escritorio.add(CCs);
        CCs.moveToFront();
    }//GEN-LAST:event_jConsultaCuartelesActionPerformed

    private void jGestionCuartelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionCuartelesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        gestionCuarteles GC = new gestionCuarteles();
        GC.setVisible(true);
        GC.getContentPane().setBackground(new Color (153, 153, 153));
        escritorio.add(GC);
        GC.moveToFront();
    }//GEN-LAST:event_jGestionCuartelesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        nuevoSiniestro sini = new nuevoSiniestro();
        sini.setVisible(true);
        escritorio.add(sini);
        sini.moveToFront();
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        consultaSiniestro sini = new consultaSiniestro();
        sini.setVisible(true);
        escritorio.add(sini);
        sini.moveToFront();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        gestionSiniestro sini = new gestionSiniestro();
        sini.setVisible(true);
        escritorio.add(sini);
        sini.moveToFront();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultaBrigada;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenuItem gestionBrigada;
    private javax.swing.JMenuItem jConsultaCuarteles;
    private javax.swing.JMenuItem jGestionCuarteles;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jmBomberoConsulta;
    private javax.swing.JMenuItem jmBomberoGestion;
    private javax.swing.JMenuItem jmBomberoNuevo;
    private javax.swing.JMenuItem jmNuevoCuartel;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem nuevaBrigada;
    // End of variables declaration//GEN-END:variables
}
